# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('tgl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priceAnalysis.Bulan')),
            ],
        ),
        migrations.AddField(
            model_name='bulan',
            name='cabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priceAnalysis.Cabe'),
        ),
    ]
